apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: gcr.io/dwk-gke-509503/todo-backend
          envFrom:
            - configMapRef:
                name: todo-db-config
            - secretRef:
                name: todo-db-secret
          env:
            - name: PORT
              value: "3000"