apiVersion: v1
kind: Secret
metadata:
    name: todo-db-secret
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1czk5RU+4jBHdjx+atNWccvboz5QbMntwnwdhw==,iv:1/qQ1ZDpquWGZ675AXoR0ENPlkSMdOEF/kUb630XBqA=,tag:bNqzxswMWkHXIQ6qZSs6PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUDhGSEk3dnFjZFZQMmFz
            UWY1SzZnRFFGMnVIMkU2QmlqM2k1ZW1hNFZrCklYeG9CejUyclp5aXVnaXNHWG5m
            TDF6YlkzZGZlZk9DZ3RvcEJFYysxaWsKLS0tIHFMRUg5eUNhenRPMlRXMTFER014
            eFArSk1EbERYcVRheGd2L3AzWVVXb0UKlemJCZZJ8w8VtuPxqSHZvnJ5fvkKpAo8
            VZ40QjnRR0NzMAe5Aen6NxcZuosPURWMyJCB94Y9z4XS3ZvUdAkGCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3k7khn55448hm7xl6hz7ze6msfk5vu380d28yt42sqqh9e4jpvq5ljtma
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-22T03:33:07Z"
    mac: ENC[AES256_GCM,data:aIuNBwG+5gqdJqaCOZizpRRJPH6hU/oeoSeEeyYRJax2UZzn1H8ZosQumQyKPJ0a2Fa8upg2bl0W3UilW1Cr4sNQ86pX0jCoOm6tzp/IHeopOy9fQnKT/p7OYhbFLsHUGQfMFrt7PJ61jRsPumJE9YeBFZuX1jfjfNC1QubwXJc=,iv:e84GY0kiaoNxPSBlNoiquRff2iYiPA32YFITXB7xrDc=,tag:qYQafYOrlFasrxPms53brQ==,type:str]
    version: 3.13.3
